administration/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('doctors', views.doctors, name='doctors-page'),
    path('files', views.files_page, name='files-page'),
    path('upload_files/<file_id>', views.upload_files_page, name='upload-files-page'),
    path('logs', views.logs_page, name='logs-page'),
    path('admin_samd', views.admin_samd, name='admin-samd'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_page, name='home'),
    path('account/', views.account, name='account'),
    # path('account/add_record', views.add_selfmonitor_record, name='add-record'),
    path('account/reception', views.ReceptionView.as_view(), name='reception'),
    path('account/reception/add/<profile_id>', views.reception_add_page, name='add-reception'),
    path('account/reception/update/<profile_id>/<note_id>', views.update_reception_page, name='update-reception'),
    path('account/records', views.records_page, name='records'),
    path('account/records/add', views.add_selfmonitor_record, name='add-record'),
    path('account/records/update/<record_id>', views.update_reception_page, name='update-record'),
    path('data_sampling', views.data_sampling_page, name='data-sampling'),
    path('update_mo_delivery/<profile_id>', views.update_mo_delivery, name='update-mo-delivery'),
    path('statistics_report', views.statistics_report, name='statistics-report'),
    path('download_report/<report_id>', views.download_report, name='download-report'),
]

med_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('administration.urls')),
    path('', include('users.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.contrib.auth.models import User
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import MaxValueValidator
import datetime
from .choices import *


class Patient(models.Model):
    user         = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name   = models.CharField("Имя", max_length=50)
    last_name    = models.CharField("Фамилия", max_length=50)
    father_name  = models.CharField("Отчество", max_length=50, blank=True)
    telephone    = PhoneNumberField('Телефонный номер', blank=True, null=True)
    email        = models.EmailField('Email', max_length=60, blank=True, null=True)
    date_updated = models.DateTimeField('Дата изменения', auto_now=True)
    
    class Meta:
        verbose_name = 'Пациент'
        verbose_name_plural = 'Пациенты'
        ordering = ['-date_updated']
    
    def __str__(self) -> str:
        return self.get_full_name()
    
    def get_full_name(self) -> str:
        return f"{self.last_name} {self.first_name} {self.father_name}".strip()


##### Medical Forms #####

class MedicalCard(models.Model):
    # personal data
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE, related_name='card')
    first_name   = models.CharField("Имя", max_length=50)
    last_name    = models.CharField("Фамилия", max_length=50)
    father_name  = models.CharField("Отчество", max_length=50, blank=True)
    date_of_birth = models.DateField('Дата рождения', blank=True, null=True)
    age = models.PositiveSmallIntegerField('Полных лет', validators=[MaxValueValidator(99)], blank=True, null=True)
    series_number_pass = models.PositiveBigIntegerField("Серия и номер паспорта", blank=True, null=True)
    when_issued = models.DateField("Когда выдан", blank=True, null=True)
    when_whom_issued = models.CharField("Кем выдан", max_length=100, blank=True, null=True)
    residence_address = models.CharField('Адрес проживания', max_length=100, blank=True, null=True)
    registration_address = models.CharField('Адрес регистрации', max_length=100, blank=True, null=True)
    territory    = models.CharField('Территория', max_length=25, choices=TERRITORY, default='Ульяновский')
    oms_policy   = models.CharField('Полис ОМС', max_length=16, blank=True, null=True)
    snils        = models.CharField('СНИЛС', max_length=11, blank=True, null=True)
    
    # contact data
    mobile_phone    = PhoneNumberField('Мобильный телефон', max_length=20, blank=True, null=True)
    home_phone    = PhoneNumberField('Домашний телефон', max_length=20, blank=True, null=True)
    work_phone    = PhoneNumberField('Рабочий телефон', max_length=20, blank=True, null=True)
    email        = models.EmailField('Адрес электронной почты', max_length=60)
    marital_status = models.CharField('Брачное состояние', default='', choices=MARITAL_STATUS, max_length=1, blank=True, null=True)
    med_org      = models.CharField('На учете МО', max_length=150, choices=MEDICAL_ORGANIZATION, blank=True, null=True)
    
    # trusted person
    trusted_person_fio = models.CharField("ФИО доверенного лица", max_length=300, blank=True, null=True)
    trusted_person_phone = PhoneNumberField('Контактный телефон', max_length=20, blank=True, null=True)
    education = models.CharField('Образование', max_length=5, choices=EDUCATION, blank=True, null=True)
    profession = models.CharField('Профессия', max_length=200, blank=True, null=True)
    work_place = models.CharField('Место работы', max_length=200, blank=True, null=True)
    disability = models.CharField('Инвалидность', max_length=200, choices=DISABILITY, blank=True, null=True)
    
    # maternity leave
    maternity_leave_start = models.DateField('Начало декретного отпуска', blank=True, null=True)
    maternity_leave_finish = models.DateField('Окончание декретного отпуска', blank=True, null=True)
    disability_certificate = models.CharField('Номер отпуска по беременности и родам', max_length=16, blank=True, null=True)
    generic_certificate_number = models.CharField('Номер родового сертификата', max_length=20, blank=True, null=True)
    generic_certificate_date = models.DateField('Дата выдачи родового сертификата', blank=True, null=True)
    
    # allergy
    allergy = models.BooleanField('Аллергическая реакция', default=False, null=True)
    allergy_description = models.CharField('Описание аллергической реакции', default='', max_length=100, blank=True, null=True)
    
    # blood fields
    mother_blood_group = models.CharField('Группа крови', max_length=1, choices=BLOOD, blank=True, null=True)
    mother_blood_rh = models.CharField('Rh-фактор', max_length=1, choices=RH, blank=True, null=True)
    mother_date_of_determination = models.DateField('Дата определения', blank=True, null=True)

    father_blood_group = models.CharField('Группа крови отца ребенка', max_length=1, choices=BLOOD, blank=True, null=True)
    father_blood_rh = models.CharField('Rh-фактор отца ребенка', max_length=1, choices=RH, blank=True, null=True)
    father_date_of_determination = models.DateField('Дата определения', blank=True, null=True)
    
    # pregnancy data
    pregnancy_count = models.PositiveSmallIntegerField('Данная беременность по счету', blank=True, validators=[MaxValueValidator(99)], null=True)
    births_by_term = models.CharField('Данные роды по счету', max_length=200, blank=True, null=True)
    gestation_period_weeks = models.PositiveSmallIntegerField('Срок беременности (недели)', validators=[MaxValueValidator(99)], blank=True, null=True)
    first_visit_date = models.DateField('Дата первой явки (взятие на учет)', blank=True, null=True)
    
    # birth data
    childbirth_date = models.DateField('Дата родов', blank=True, null=True)
    childbirth_gestation_period = models.PositiveSmallIntegerField('Срок беременности родов (недели)', validators=[MaxValueValidator(99)], blank=True, null=True)
    med_org      = models.CharField('Медицинская организация', max_length=150, choices=MEDICAL_ORGANIZATION, blank=True, null=True)
    
    # diagnosis
    diagnosis = models.CharField('Основной диагноз', max_length=200, blank=True, null=True)
    complications = models.CharField('Осложнения данной беременности', max_length=200, blank=True, null=True)
    
    # other diseases
    somatic_diseases = models.CharField('Соматические заболевания', max_length=200, blank=True, null=True)
    gynecological_diseases = models.CharField('Гинекологические  заболевания', max_length=200, blank=True, null=True)
    
    class Meta:
        verbose_name = 'Медицинская карта'
        verbose_name_plural = 'Медицинские карты'
    
    def get_full_name(self) -> str:
        return f"{self.last_name} {self.first_name} {self.father_name}"
    
    def __str__(self) -> str:
        return self.get_full_name()


class ObstetricRisk(models.Model):
    card = models.ForeignKey(MedicalCard, on_delete=models.CASCADE, related_name='risks')
    visit = models.CharField('Срок явки', max_length=5, choices=VISIT, blank=True, null=True)
    
    class Meta:
        verbose_name = 'Акушерский риск'
        verbose_name_plural = 'Акушерские риски'
    
    def __str__(self) -> str:
        return self.card.__str__() + ' ' + self.visit


class ComplicationRisk(models.Model):
    risk = models.ForeignKey(ObstetricRisk, on_delete=models.CASCADE, related_name='complications')
    complication_risk = models.CharField('Риск осложнениний', max_length=150, blank=True, null=True)
    risk_value = models.PositiveSmallIntegerField('Значение индивидуального риска', blank=True, null=True)
    
    class Meta:
        verbose_name = 'Риск осложнения'
        verbose_name_plural = 'Риски осложнений'
    
    def __str__(self) -> str:
        return self.complication_risk


class PregnancyOutcome(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='pregnancy_outcome')
    pregnancy_count = models.PositiveSmallIntegerField('Беременность по счету', validators=[MaxValueValidator(99)])
    childbirth_date = models.DateTimeField('Дата исхода беременности', blank=True, null=True)
    pregnancy_outcome = models.CharField('Исход беременности', max_length=10, choices=PREGNANCY_OUTCOME, blank=True, null=True)
    
    if_childbirth = models.CharField('Роды', max_length=10, choices=CHILDBIRTH, blank=True, null=True)
    
    if_abortion = models.CharField('Аборт', max_length=10, choices=ABORTION, blank=True, null=True)
    
    # if death
    death_time = models.DateTimeField('Смерть', blank=True, null=True)
    disease = models.CharField('Причина смерти (шифр по МКБ-10)', max_length=10, blank=True, null=True)
    
    gestation_period_weeks = models.PositiveSmallIntegerField('Срок беременности (недели)', validators=[MaxValueValidator(99)], blank=True, null=True)
    number_of_fetuses = models.PositiveSmallIntegerField('Количество плодов', validators=[MaxValueValidator(10)], blank=True, null=True)
    
    child_gender = models.CharField('Пол ребенка', max_length=10, choices=GENDERS, blank=True, null=True)
    child_weight = models.PositiveSmallIntegerField('Вес ребенка (г.)', blank=True, null=True)

    class Meta:
        verbose_name = 'Исход беременности'
        verbose_name_plural = 'Исходы беременностей'
        ordering = ['pregnancy_count']
    
    def __str__(self) -> str:
        return self.patient.get_full_name() + " count: " + str(self.pregnancy_count)


# Наблюдения во время настоящей беременности

class CurrentPregnancy(models.Model):
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE, related_name='current_pregnancy')


class Pelviometry(models.Model):
    current_pregnancy = models.ForeignKey(CurrentPregnancy, on_delete=models.CASCADE, related_name='pelviometry')
    date = models.DateField('Дата', blank=True, null=True)
    dsp = models.PositiveSmallIntegerField('D.sp. (см)', validators=[MaxValueValidator(1000)], blank=True, null=True)

administration/forms.py
from django import forms
from .models import Files


class FileUploadForm(forms.ModelForm):
    class Meta:
        model = Files
        fields = ('title', 'description', 'document')
        widgets = {
            'document': forms.FileInput(attrs={'required': False,'class': 'form-control'})
        }

administration/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from typing import Any
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from home.models import Doctor, ChangeControlLog
from .models import Files
from home.models import SAMD
from .forms import FileUploadForm
from django.views.generic import CreateView
from django.contrib import messages
from django.core.paginator import Paginator
from home.views import add_log
from med_system.funcs import get_and_add_cookie
from urllib.parse import quote, unquote
import json

def user_is_admin(user):
    return not (hasattr(user, 'doctor') or hasattr(user, 'patient'))

class UserIsAdmin(UserPassesTestMixin):
    def test_func(self):
        user_obj = self.request.user
        return not (hasattr(user_obj, 'doctor') or hasattr(user_obj, 'patient'))


@login_required
@user_passes_test(user_is_admin)
def doctors(request: HttpRequest):
    template_name: str = 'administration/doctors.html'
    page_number: int = request.GET.get('page', 1)
    to_add = f'/doctors!Доктора'
    
    prev_data = request.POST.dict()
    if len(prev_data) < 1:
        context = { 'prev_data': json.loads(unquote(request.COOKIES.get('prev_data', '{}'))) }
    else:
        context = { 'prev_data': prev_data }
    
    if request.method == 'POST':
        users = Doctor.objects
        for f in tuple(request.POST.items())[1:]:
            if len(f[1]) > 0:
                match f[0]:
                    case 'last_name':
                        users = users.filter(last_name__startswith=f[1])
                    case 'first_name':
                        users = users.filter(first_name__startswith=f[1])
                    case 'father_name':
                        users = users.filter(father_name__startswith=f[1])
                    case _:
                        users = users.filter(**dict((f,)))
        if isinstance(users, Doctor.objects.__class__):
            if request.POST['role'] == '':
                users = users.all()
            else:
                users = []
        page_number = 1
    else:
        users = Doctor.objects.all()
    
    paginator = Paginator(users, 8)
    page_obj = paginator.get_page(page_number)
    context |= { 'users': paginator.page(page_number), 'page_obj': page_obj, 'paginator': paginator }
    resp = render(request, template_name, context)
    resp.set_cookie('nav', quote(to_add, safe='!#/'), samesite='strict')
    resp.set_cookie('prev_data', quote(str(context.get('prev_data')).replace("'", '"')), samesite='strict')
    return resp

@login_required
def files_page(request):
    to_add: str = f'/files!Файлы'
    
    if request.method == "POST":
        id = request.POST.get('delete_id')
        Files.objects.get(pk=id).delete()
    
    files = Files.objects.all()
    
    resp = render(request, 'administration/files.html', { 'files': files })
    resp.set_cookie('nav', quote(to_add, safe='!#/'), samesite='strict')
    return resp


def upload_files_page(request: HttpRequest, file_id: int) -> HttpResponse:
    template_name: str = 'administration/upload_files.html'
    success_url: str = reverse_lazy('files-page')
    
    if request.method == "POST":
        if int(file_id) > -1:
            file = Files.objects.get(pk=file_id)
            form = FileUploadForm(request.POST, request.FILES, instance=file)
        else:
            form = FileUploadForm(request.POST, request.FILES)
        
        if form.is_valid():
            form.save(commit=True)
            add_log(request.user, f'Добавлен файл.', '-', '-', f'Файл {form.cleaned_data["title"]} был создан.')
            messages.success(request, message='Файл успешно добавлен')
            return redirect(success_url)
        else:
            return render(request, template_name, { 'form': form })
    
    context = {}
    if int(file_id) > -1:
        file = Files.objects.get(pk=file_id)
        form = FileUploadForm(request.POST, request.FILES, instance=file)
    else:
        context = { "new_file": 1 }
        form = FileUploadForm(request.POST, request.FILES)
    context |= { 'form': form }
    return render(request, template_name, context)


# class ChangeLogsView(UserIsAdmin, LoginRequiredMixin, ListView):
def logs_page(request: HttpRequest):
    template_name: str = 'administration/change_logs.html'
    to_add = '/logs!Жунал изменений'
    page_number: int = request.GET.get('page', 1)
    
    logs = ChangeControlLog.objects.all()
    paginator = Paginator(logs, 5)
    page_obj = paginator.get_page(page_number)
    context = { 'logs': paginator.page(page_number), 'page_obj': page_obj, 'paginator': paginator }
    resp = render(request, template_name, context)
    resp.set_cookie('nav', quote(to_add, safe='!#/'), samesite='strict')
    return resp


def admin_samd(request: HttpRequest) -> HttpResponse:
    template_name: str = 'administration/admin_samd.html'
    samd_docs = SAMD.objects.all()
    to_add = f'#/samd/!СЭМД документы'
    resp = render(request, template_name, { 'samd_docs': samd_docs })
    return get_and_add_cookie(request, to_add, resp)

administration/templates/administration/admin_page.html
{% extends 'home/base.html' %}

{% block content %}
<div class="admin__page__block center_div">
    <div class="">
        <form action="" method="post">
            {% csrf_token %}
            <div class="fields fileds-in-row">
                <div class="fields__input">
                    <div class="fields__input__field">
                        <input type="text" name="search">
                    </div>
                </div>
                {% if btn %}
                <div class="submit-btn">
                    <button type="submit">{{ btn }}</button>
                </div>
                {% else %}
                <div class="submit-btn">
                    <button type="submit">Искать</button>
                </div>
                {% endif %}
            </div>
        </form>
    </div>
    
    <div class="user__block">
        {% for user_i in page_obj.object_list %}
            <div class="user__block__row center_div">
                <div class="user__block__element">
                    <p>ФИО: {{ user_i.get_full_name }}</p>
                </div>
                {% if user_i.user.doctor %}
                    <div class="user__block__element">
                        <p>Доктор</p>
                    </div>
                {% else %}
                    <div class="user__block__element">
                        <p>Пациент</p>
                    </div>
                {% endif %}
                <div class="user__block__element">
                    <p><a href="{% url 'profile' user_i.user.pk %}">Профиль</a></p>
                </div>
            </div>
        {% endfor %}
    </div>
    
    {% if page_obj.has_other_pages %}
        <div class="paginate center_paginate">
            {% if page_obj.has_previous %}
            <div class="paginate__element">
                <a href="?page=1">Первая</a>
            </div>
            <div class="paginate__element">
                <a href="?page={{ page_obj.previous_page_number }}">Пред.</a>
            </div>
            {% endif %}
            
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                <div class="paginate__element">
                    <span>{{ num }}</span>
                </div>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <div class="paginate__element">
                    <a href="?page={{ num }}">{{ num }}</a>
                </div>
                {% endif %}
            {% endfor %}
        
            {% if page_obj.has_next %}
            <div class="paginate__element">
                <a href="?page={{ page_obj.next_page_number }}">След.</a>
            </div>
            <div class="paginate__element">
                <a href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
            </div>
            {% endif %}
        </div>
    {% endif %}
</div>
{% endblock %}

administration/templates/administration/admin_samd.html
{% extends 'home/base.html' %}

{% block content %}
<div class="back__button">
    <button type="button" onclick="history.back()" class="btn">Вернуться</button>
</div>

<div class="block__profile__disease border_div">
    <div class="block__lines">
        <table class="table">
            <thead>
                <tr>
                    <th>Доктор</th>
                    <th>ФИО пациента</th>
                    <th>Дата рождения пациента</th>
                    <th>Дата создания</th>
                    <th>Медицинская организация</th>
                    <th>Тип СМС</th>
                    <th>Статус СМС</th>
                    <th>Подпись</th>
                </tr>
            </thead>
            <tbody>
                {% for doc in samd_docs %}
                <tr>
                    <td><p>{{ doc.doctor.get_full_name }}</p></td>
                    <td><p>{{ doc.patient.get_full_name }}</p></td>
                    <td><p>{{ doc.patient.card.date_of_birth }}</p></td>
                    <td><p>{{ doc.create_date }}</p></td>
                    <td><p>{{ doc.get_med_org_display }}</p></td>
                    <td><p>{{ doc.get_sms_type_display }}</p></td>
                    <td><p>{{ doc.get_sms_status_display }}</p></td>
                    <td><p>{% if doc.signed %}Подписано{% else %}Не подписано{% endif %}</p></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

administration/templates/administration/change_logs.html
{% extends 'home/base.html' %}

{% block content %}

<div class="logs">
    {% for log in logs %}
        <div class="logs__row">
            <div class="logs__element">
                <p><strong>Кто изменил:</strong> {{ log.who_changed }}</p>
            </div>
            <div class="logs__element">
                <p><strong>Кого изменил:</strong> {{ log.modified_model }}</p>
            </div>
            <div class="logs__element">
                <p><strong>Тип изменения:</strong> {{ log.change_type }}</p>
            </div>
    
            {% if log.before != '-' %}
            <div class="logs__element">
                <p><strong>Было:</strong> <ul class="log">{{ log.before }}</ul></p>
            </div>
            {% endif %}
    
            {% if log.after != '-' %}
            <div class="logs__element">
                <p><strong>Стало:</strong> <ul class="log">{{ log.after }}</ul></p>
            </div>    
            {% endif %}

            <div class="logs__element">
                <p><strong>Дата изменения:</strong> {{ log.date_created }}</p>
            </div>
        </div>
    {% endfor %}
</div>

<div class="paginate">
    {% if page_obj.has_previous %}
        <div class="paginate__element">
            <a href="?page=1">First</a>
        </div>
        <div class="paginate__element">
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </div>
    {% endif %}
    
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <div class="paginate__element">
                <span>{{ num }}</span>
            </div>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <div class="paginate__element">
                <a href="?page={{ num }}">{{ num }}</a>
            </div>    
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <div class="paginate__element">
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
        </div>
        <div class="paginate__element">
            <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        </div>
    {% endif %}
</div>


<script type="text/javascript">
    (function () {
        ul = document.getElementsByClassName('log')
        for (let li of ul) {
            li_list = li.innerHTML.split(';').slice(0, -1)
            HTML_string = ''
            for (let li_data of li_list) {
                HTML_string += '<li>' + li_data + '</li>'
            }
            li.innerHTML = HTML_string
        }
    }())
</script>

{% endblock %}

administration/templates/administration/doctors.html
{% extends 'home/base.html' %}

{% block content %}

<div class="title__block center_div">
    <h2>Доктора</h2>
</div>

<div class="">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="fields">
            <div class="" style="width: 40%">
                <div class="border_div center_div">
                    <div class="width_100 search_filters_container">
                        <div class="search_filters">
                            <label for="last_name"><strong>Фамилия:</strong></label>
                            <input type="text" name="last_name" value="{{ prev_data.last_name }}" placeholder="Фамилия">
                            <label for="first_name"><strong>Имя:</strong></label>
                            <input type="text" name="first_name" value="{{ prev_data.first_name }}" placeholder="Имя">
                        </div>
                        <div class="search_filters">
                            <label for="father_name"><strong>Отчество:</strong></label>
                            <input type="text" name="father_name" value="{{ prev_data.father_name }}" placeholder="Отчество">
                            <label for="role"><strong>Должность врача:</strong></label>
                            <select name="role" id="role">
                                <option value="" selected="">Все</option>
                                <option value="obstetrician-gynecologist">Акушер-гинеколог</option>
                                <option value="therapist">Терапевт</option>
                                <option value="dentist">Стоматолог</option>
                                <option value="ophthalmologist">Офтальмолог</option>
                                <option value="specialist">Специалист</option>
                                <option value="pediator">Педиатор</option>
                                <option value="assistant">Лаборант</option>
                                <option value="nurse">Медсестра</option>
                                <option value="receptionist">Регистратор</option>
                            </select>
                        </div>
                    </div>
                    <div class="">
                        <button type="submit" class="btn">Искать</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="center_div" style="margin: 50px 0">
    <div class=" border_div" style="width: 70%">
        <div class="block__lines">
            <table class="table search_field_table">
                <thead>
                    <tr>
                        <th><strong>Фамилия:</strong></th>
                        <th><strong>Имя:</strong></th>
                        <th><strong>Отчество:</strong></th>
                        <th><strong>Специальность</strong></th>
                        <th><strong>Медицинская организация</strong></th>
                        <th><strong>Ссылка на профиль</strong></th>
                    </tr>
                </thead>
                <tbody>
                    {% for doctor in users %}
                    <tr>
                        <td>{{ doctor.last_name }}</td>
                        <td>{{ doctor.first_name }}</td>
                        <td>{{ doctor.father_name }}</td>
                        <td>{{ doctor.get_role_display }}</td>
                        <td>{{ doctor.get_med_org_display }}</td>
                        <td><a href="{% url 'profile' doctor.user.id %}">Профиль</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% if page_obj.has_other_pages %}
    <div class="paginate center_paginate">
        {% if page_obj.has_previous %}
        <div class="paginate__element">
            <a href="?page=1">Первая</a>
        </div>
        <div class="paginate__element">
            <a href="?page={{ page_obj.previous_page_number }}">Пред.</a>
        </div>
        {% endif %}
        
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
            <div class="paginate__element">
                <span>{{ num }}</span>
            </div>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <div class="paginate__element">
                <a href="?page={{ num }}">{{ num }}</a>
            </div>
            {% endif %}
        {% endfor %}
    
        {% if page_obj.has_next %}
        <div class="paginate__element">
            <a href="?page={{ page_obj.next_page_number }}">След.</a>
        </div>
        <div class="paginate__element">
            <a href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
        </div>
        {% endif %}
    </div>
{% endif %}
{% endblock %}

administration/templates/administration/files.html
{% extends 'home/base.html' %}

{% block content %}
<div class="file__page__block center_div">
    {% if user.is_superuser %}
        <div class="upload-file btn">
            <a href="{% url 'upload-files-page' -1 %}">Загрузить Файлы</a>
        </div>
    {% endif %}
    <div class="outer_div">
        {% for f in files %}
        <div class="border_div margin-bottom-20">
            <div class="files__block center_div">
                    <div class="files__block__element">
                        <p><strong>Название:</strong> {{ f.title }}</p>
                    </div>
                    <div class="files__block__element">
                        <p><strong>Описание:</strong> {{ f.description }}</p>
                    </div>
                    <div class="three_btns">
                        <a href="{{ f.document.url }}" download class="btn">Скачать файл</a>
                        {% if user.is_superuser %}
                            <a href="{% url 'upload-files-page' f.pk %}" class="btn">Изменить</a>
                            <form action="" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="delete_id" id="" value="{{ f.pk }}">
                                <button type="submit" class="btn">Удалить</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}